In [1]:
# 1
import numpy as np


arr = np.array([10, 20, 30, 40, 50])


arr_add = arr + 2
print("After adding 2 to all elements:", arr_add)

arr_multiply = arr * 3
print("After multiplying all elements by 3:", arr_multiply)

arr_divide = arr / 2
print("After dividing all elements by 2:", arr_divide)


After adding 2 to all elements: [12 22 32 42 52]
After multiplying all elements by 3: [ 30  60  90 120 150]
After dividing all elements by 2: [ 5. 10. 15. 20. 25.]


In [3]:
# 2
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])[::-1]
print("Reversed array:", arr)

def most_frequent(arr):
    values, counts = np.unique(arr, return_counts=True)
    most_frequent_value = values[np.argmax(counts)]
    return most_frequent_value, np.where(arr == most_frequent_value)[0]

a, b = np.array([1,2,3,4,5,1,2,1,1,1]), np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

print("Most frequent value in a:", most_frequent(a))
print("Most frequent value in b:", most_frequent(b))



Reversed array: [5 4 6 3 2 1]
Most frequent value in a: (1, array([0, 5, 7, 8, 9]))
Most frequent value in b: (1, array([0, 1, 2]))


In [4]:
# 3


two_d_arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print("2D array:")
print(two_d_arr)
print("1st row, 2nd column:", two_d_arr[0, 1])
print("3rd row, 1st column:", two_d_arr[2, 0])

2D array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
1st row, 2nd column: 20
3rd row, 1st column: 70


In [5]:
# 4
arr = np.linspace(10, 100, 25)
print("\nArray:", arr)

# Print array properties
print("Shape:", arr.shape)
print("Total elements:", arr.size)
print("Data type:", arr.dtype)
print("Total bytes consumed:", arr.nbytes)

# Transpose using reshape
transposed_array = arr.reshape(25, 1)
print("\nTransposed using reshape:\n", transposed_array)

# Transpose using T attribute
transposed_T = arr.T
print("\nTransposed using T attribute:\n", transposed_T)



Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes consumed: 200

Transposed using reshape:
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transposed using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [6]:
# 5
ucs420_sushant = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])


print("Mean:", np.mean(ucs420_sushant))
print("Median:", np.median(ucs420_sushant))
print("Max:", np.max(ucs420_sushant))
print("Min:", np.min(ucs420_sushant))
print("Unique elements:", np.unique(ucs420_sushant))


reshaped_ucs420_sushant = ucs420_sushant.reshape(4, 3)
print("\nReshaped to 4x3:\n", reshaped_ucs420_sushant)

resized_ucs420_sushant = np.resize(ucs420_sushant, (2, 3))
print("\nResized to 2x3:\n", resized_ucs420_sushant)


Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped to 4x3:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized to 2x3:
 [[10 20 30]
 [40 50 60]]
